-- Weight Logs
CREATE TABLE weight_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id),
  date DATE NOT NULL,
  weight FLOAT NOT NULL,
  body_fat FLOAT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Meals
CREATE TABLE meals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id),
  date DATE NOT NULL,
  meal_type TEXT NOT NULL,
  food_name TEXT NOT NULL,
  calories INT DEFAULT 0,
  protein INT DEFAULT 0,
  carbs INT DEFAULT 0,
  fat INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Workout Plans
CREATE TABLE workout_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id),
  day_of_week TEXT NOT NULL,
  exercise TEXT NOT NULL,
  sets INT DEFAULT 3,
  reps INT DEFAULT 10,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Workout Logs
CREATE TABLE workout_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id),
  date DATE NOT NULL,
  exercise TEXT NOT NULL,
  sets INT DEFAULT 3,
  reps INT DEFAULT 10,
  weight FLOAT DEFAULT 0,
  completed BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
